# Generated by Django 2.0.3 on 2018-04-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='numOrder',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='probAnswer',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='problem',
            name='probQuestion',
            field=models.TextField(max_length=2000),
        ),
    ]
