# Generated by Django 2.0.3 on 2018-04-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='probQuestion',
            field=models.TextField(max_length=2000),
        ),
    ]
