# Generated by Django 2.0.3 on 2018-04-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='numOrder',
            field=models.IntegerField(default=0),
        ),
    ]
