# Generated by Django 2.0.3 on 2018-04-25 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_auto_20180422_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pack',
            old_name='fininshed',
            new_name='finished',
        ),
    ]
