# Generated by Django 2.0.3 on 2018-04-06 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_app', '0001_initial'),
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sectionNum', models.CharField(max_length=20)),
                ('maxCapacity', models.IntegerField(default=0)),
                ('numEnrolled', models.IntegerField(default=0)),
                ('openDate', models.DateTimeField(verbose_name='Open Date')),
                ('closeDate', models.DateTimeField(verbose_name='Close Date')),
                ('professorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.IntegerField(default=0)),
                ('attempts', models.IntegerField(default=0)),
                ('problemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.Problem')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='progressID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.Progress'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='studID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.Student'),
        ),
        migrations.AddField(
            model_name='connection',
            name='courseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.Course'),
        ),
        migrations.AddField(
            model_name='connection',
            name='packID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.Pack'),
        ),
    ]
