# Generated by Django 2.0.3 on 2018-04-28 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0003_auto_20180425_1040'),
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='progressID',
        ),
        migrations.AddField(
            model_name='progress',
            name='enrollmentID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='course_app.Enrollment'),
        ),
        migrations.AddField(
            model_name='progress',
            name='packID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='game_app.Pack'),
        ),
    ]
