# Generated by Django 2.0.3 on 2018-04-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='classCode',
            field=models.CharField(default=0, max_length=30, unique=True),
        ),
    ]
